apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: nvidia-gpu-driver
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/ebelarte-tenant/nvidia-gpu-driver/nvidia-gpu-driver@sha256:e76a9a31828a5cbbe3ee4e3733cf82a295e9a9faf9ceba905b9f223f0c192c5f
        name: container-image
        resources: {}
status: {}
