apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nvidia-gpu-driver
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nvidia-gpu-driver
    app.kubernetes.io/part-of: nvidia-gpu-driver
  name: nvidia-gpu-driver
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: nvidia-gpu-driver
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: nvidia-gpu-driver
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/ebelarte-tenant/nvidia-gpu-driver/nvidia-gpu-driver@sha256:0017bf85f4fdb2aa6a089566795514d363ad2b51d8fd49c857c062afd048813b
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
