apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nvidia-gpu-driver
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nvidia-gpu-driver
    app.kubernetes.io/part-of: nvidia-gpu-driver
  name: nvidia-gpu-driver
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: nvidia-gpu-driver
status:
  loadBalancer: {}
